### ISSUE TITLE
error

### ISSUE THREAD

**Issue by YYH201905555510** [hku-mars/ROG-Map#10]
=== GCC Version ===
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
=== G++ Version ===
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
=== Eigen Version ===
Version: 3.3.7-2

CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/home/yyh/miniconda3/envs/YOUR_ENV_NAME/bin/python3
  "/opt/ros/noetic/share/catkin/cmake/parse_package_xml.py"
  "/opt/ros/noetic/share/catkin/cmake/../package.xml"
  "/home/yyh/build/catkin/catkin_generated/version/package.cmake") returned
  error code No such file or directory
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_package_xml.cmake:74 (safe_execute_process)
  /opt/ros/noetic/share/catkin/cmake/all.cmake:168 (_catkin_package_xml)
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:58 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/yyh/build/CMakeFiles/CMakeOutput.log".
See also "/home/yyh/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:320：cmake_check_build_system] 错误 1
Invoking "make cmake_check_build_system" failed

**Comment by RENyunfan** [comment]
Hi there,

It seems like a conflict with your miniconda. You can try to install some necessary pkg in your conda environment such as 

```bash
pip install empy==3.3.4 rospkg rospy catkin_pkg
```

Or you can simply disable the miniconda and use the system's default Python to build. 

Remember to delete the `build` and `devel` folder when you retry the `catkin_make` command.
