### ISSUE TITLE
looking forward to your code

### ISSUE THREAD

**Issue by panyaoqiang** [hku-mars/ROG-Map#5]
I'm really looking forward to it. When can I expect to see the code? I can't wait.

**Comment by RENyunfan** [comment]
Thank you for your patience. I apologize for the delay caused by unforeseen paperwork. I am going to release a preview version soon.

**Comment by panyaoqiang** [comment]
您好，您的邮件耀强已经收到，辛苦了。

**Comment by RENyunfan** [comment]
Thank you for your patience. We are excited to announce that the preview version of ROG-Map is now open source! You can access it from [ROG-Map](https://github.com/hku-mars/ROG-Map)

Feel free to give it a try, and we would love to hear your feedback.

**Comment by panyaoqiang** [comment]
您好，您的邮件耀强已经收到，辛苦了。
