### ISSUE TITLE
How to track the planned path and make the robot move?

### ISSUE THREAD

**Issue by JACKLiuDay** [hku-mars/ROG-Map#6]
Thank you very much for your work. I want to use ROG-Map and utilize the planned path to make the robot move. Currently, I can use mid360 to generate the ROG-Map and plan a path to the target point. So how can I make the robot follow this path?

**Comment by RENyunfan** [comment]
Thank you for your feedback. You can control the drone using the /planning/pos_cmd topic, which utilizes the quadrotor_msgs/PositionCommand message type. I have updated the details in the README for you and anyone else who wishes to control the drone using ROS topics.

**Comment by JACKLiuDay** [comment]
> Thank you for your feedback. You can control the drone using the `/planning/pos_cmd` topic, which utilizes the `quadrotor_msgs/PositionCommand` message type. I have updated the details in the README for you and anyone else who wishes to control the drone using ROS topics.

Hi, thank you for your quick reply. I will try it with the simulation. I plan to use the MPC planner provided by ROS to follow the A* path generated in the ROG-Map. Do you have any good suggestions for trajectory tracking methods?

**Comment by RENyunfan** [comment]
Although it cannot be directly applied in ROG-Map with its current released version, you can refer to our previous work, [IPC](https://github.com/hku-mars/IPC), which includes a C++ implementation of linear MPC for quadrotors.

**Comment by JACKLiuDay** [comment]
Thank you for your suggestion. I've been looking into the application of MPC in path tracking recently. I will try the approach used in IPC project. It seems like a good idea.
