### ISSUE TITLE
How to control the move of drones？

### ISSUE THREAD

**Issue by zxin111** [hku-mars/ROG-Map#8]
Thank you very much for your work. We are using the ROS topic /planning/pos_cmd to control the drone's movement. The pos_cmd topic publishes position, acceleration, and yaw. Additionally, the flatness.forward function has calculated the thr, but the drone still cannot move forward. What could be the other possible issues?

**Comment by zxin111** [comment]
Thank you very much for your patient reply. When I run your call_pos_cmd.sh script, the following message appears:
bash scripts/call_pos_cmd.sh 1 0 1.5
ERROR: invalid message type: quadrotor_msgs/PositionCommand.
If this is a valid message type, perhaps you need to type 'rosmake quadrotor_msgs

The message we released： pub_pos_cmd = nh.advertise<quadrotor_msgs::PositionCommand>("/planning/pos_cmd", 1);

Are quadrotor_msgs: PositionCommand and quadrotor_msgs/PositionCommand the same here? Among them, quadrotor_msgs: PositionCommand is located in the PositionCommand under mars_quadrotor_msgs.

And we have already turned off the keyboard control feature.

**Comment by RENyunfan** [comment]
Before running the script, you should run `source devel/setup.bash` at the workspace that contains the mars_quadrotor_msgs. Have a try.

**Comment by RENyunfan** [comment]
Please use mars_quadrotor_msgs from our repository instead of the original quadrotor_msgs. Using the wrong message type may cause topic publication to fail due to an MD5 checksum mismatch.

**Comment by zxin111** [comment]
Now I have a question, the position received by the drone is the position to be moved in the next moment, not the current position, so even if it receives speed, the drone will not move. Is this understanding correct? The following is the function for publishing the planning/pos_cmd topic. Can the drone move by changing its position here to the next moment in its trajectory?

void cmdCallback(const geometry_msgs::Twist& msg)
{
    quadrotor_msgs::PositionCommand pos_cmd_msg;

    pos_cmd_msg.position.x = current_position(0);
    pos_cmd_msg.position.y = current_position(1);
    pos_cmd_msg.position.z = current_position(2); 

    pos_cmd_msg.velocity.x = msg.linear.x; 
    pos_cmd_msg.velocity.y = 0.0; 
    pos_cmd_msg.velocity.z = 0.0; 
 
   
    pos_cmd_msg.acceleration.x = 0.0; 
    pos_cmd_msg.acceleration.y = 0.0; 
    pos_cmd_msg.acceleration.z = 0.0; 

  
   
    pos_cmd_msg.angular_velocity.x = 0.0;
    pos_cmd_msg.angular_velocity.y = 0.0; 
    pos_cmd_msg.angular_velocity.z = 0.0; 

    pos_cmd_msg.yaw = 0.0;
 
 
    pub_pos_cmd.publish(pos_cmd_msg);
}

**Comment by RENyunfan** [comment]
In this perfect simulation, the drone follows only the desired position and acceleration (used for attitude control). The velocity control is unavailable. To move the drone, simply publish the next desired position.

**Comment by zxin111** [comment]
Sorry to bother you again.From your code single_drone_os128.launch, you can change the type of lidar to select the one you want to use. Can you tell me where you loaded mid360 from in the code?

**Comment by RENyunfan** [comment]
> Sorry to bother you again.From your code single_drone_os128.launch, you can change the type of lidar to select the one you want to use. Can you tell me where you loaded mid360 from in the code?

This aspect is beyond the scope of ROG-Map. For further reference, please consult [MARSIM](https://github.com/hku-mars/MARSIM).

**Comment by zxin111** [comment]
Thank you very much.

**Comment by zxin111** [comment]
When setting the target point, we sometimes encounter ROS-ERROR ([A*]: Start pos collide or out of bound), How to set the target point better in unknown situations？Also, the robot only tends to turn when it encounters an obstacle immediately. Is this related to the expansion coefficient setting？
